#!/bin/bash
rm -f `find -iname "*.bck"` 
rm -f `find -iname "*.o"`
rm -f `find -iname "munich"`

# if [ "$1" = "all" ]; then
#    lst=`ls -d tmp* 2>/dev/null`
#    for di in ${lst}; do
#       [ -d ${di} ] && { echo "removing ${di}...";  rm -rf ${di}; }
#    done
#    rm -rf ./exe-*
# fi
# echo "Remaining .nc files:"
# find -iname "*.nc"
# echo -n "Total directory space: "
# du -sh .
