# Copyright (C) 2007-2008, ENPC - INRIA - EDF R&D
#     Author(s): Vivien Mallet
#
# This file is part of the air quality modeling system Polyphemus.
#
# Polyphemus is developed in the INRIA - ENPC joint project-team CLIME and in
# the ENPC - EDF R&D joint laboratory CEREA.
#
# Polyphemus is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Polyphemus is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# For more information, visit the Polyphemus web site:
#      http://cerea.enpc.fr/polyphemus/

import os

execfile(polyphemus_path + "include/common/SConstruct_include")

execfile(polyphemus_path + "include/common/SConstruct_main")

# Informs SCons on the targets to be built. It is assumed that all targets
# have the same dependencies.
for filename in target_list:
    program_name = '.'.join(os.path.splitext(os.path.basename(filename))[:-1])
    env.Program(program_name, [filename] + dependency_list)
