#!/bin/bash

current_dir=$PWD

for i in "$@"
do
case $i in
# Read the option to choose whether MPI is taken into account.
# Accepted values: yes or no
# Default: mpi = yes
    -m=*|--mpi=*)
    mpi="${i#*=}"
    shift
    ;;
# Read the option for Chemistry kinetic mechanism.
# Accepted values: racm, racm2, cb05
# Default: chemistry=cb05
    -c=*|--chemistry=*)
    chemistry="${i#*=}"
    shift
    ;;
# Read the option to debug.
    -d)
        profile="debug"
        echo "=== DEBUG MODE ==="
    shift
    ;;
esac
done

if [ -z $mpi ]; then
    mpi="yes"
fi
echo "MPI: $mpi"

if [ -z $chemistry ]; then
    chemistry="cb05"
fi

if [ -z $profile ]; then
    profile="fast"
fi


# Compile SSH-Aerosol modele
cd ../../include/ssh-aerosol
./compile -s=yes -c=$chemistry

echo "==================================="
echo "Completed: compiling of SSH-Aerosol"
echo "==================================="

cd $current_dir

scons -j6 mpi=$mpi profile=$profile 

echo "=============================="
echo "Completed: compiling of MUNICH"
echo "=============================="
