#!/usr/bin/env bash

DIR=munich-git
CWD=`pwd`

if [ -d $DIR ]; then
    echo Directory $DIR already exists. Please remove it or choose another directory.
    exit 1
fi

git clone https://github.com/cerea-lab/munich.git $DIR
git clone https://github.com/sshaerosol/ssh-aerosol.git $DIR/include/ssh-aerosol
git clone https://gitlab.com/polyphemus/atmodata.git $DIR/include/AtmoData
git clone https://gitlab.com/polyphemus/seldondata.git $DIR/include/SeldonData
git clone https://gitlab.com/polyphemus/talos.git $DIR/include/Talos
git clone https://gitlab.com/polyphemus/atmopy.git $DIR/include/atmopy

